### ISSUE TITLE
事件元素抽取

### ISSUE THREAD

**Issue by gaowenxin95** [gaozhanfire/CCF-BDCI2019_Entity_Discovery#2]
请问，赛道2的：**CCKS 2020：面向金融领域的篇章级事件主体与要素抽取（二）篇章事件要素抽取**有开源嘛

想求一份要素抽取的basline

@gaozhanfire

**Comment by gaozhanfire** [comment]
抱歉，暂时还没有参加ccks

**Comment by gaowenxin95** [comment]
好啊
